"""add entra_registrations

Revision ID: 8e8baf37c76a
Revises: cc0245339f27
Create Date: 2026-08-31 21:10:56.144861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import oracle

# revision identifiers, used by Alembic.
revision: str = '8e8baf37c76a'
down_revision: Union[str, Sequence[str], None] = 'cc0245339f27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Hand-corrected after autogenerate: it also proposed dropping the
    # already-tested Postgres partial unique index on identity_mappings
    # and replacing it with the Oracle-style expression-index form — a
    # false positive from having both dialect variants (same index name,
    # .ddl_if(dialect=...)-gated) present in models.py, which autogenerate
    # doesn't understand is intentional per-dialect branching. That drop/
    # recreate is unrelated to this migration's actual purpose and removed
    # entirely; adding entra_registrations shouldn't touch it.
    op.create_table('entra_registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('environment', sa.String(length=10), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('audience', sa.String(length=120), nullable=False),
    sa.Column('subject_claim', sa.String(length=60), server_default='preferred_username', nullable=False),
    sa.Column('resource_server_url', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True).with_variant(oracle.TIMESTAMP(timezone=True), 'oracle'), server_default=sa.func.now(), nullable=False),
    sa.Column('created_by', sa.String(length=320), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True).with_variant(oracle.TIMESTAMP(timezone=True), 'oracle'), nullable=True),
    sa.Column('updated_by', sa.String(length=320), nullable=True),
    sa.CheckConstraint("environment IN ('dev', 'test', 'uat', 'prod')", name='ck_entra_registrations_environment'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('environment', name='ux_entra_registrations_one_per_environment')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entra_registrations')
    # ### end Alembic commands ###
