"""initial identity mapping schema

Revision ID: cc0245339f27
Revises: 
Create Date: 2026-08-31 15:15:39.053103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import oracle

# revision identifiers, used by Alembic.
revision: str = 'cc0245339f27'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # NOTE: hand-corrected after autogenerate — see the migration's own
    # docstring context in the session that produced it. Autogenerate
    # reflects *concrete* defaults from the live database it ran against,
    # not the portable constructs models.py actually uses, so it emitted
    # sa.text('now()') and sa.text('true') here — both Postgres-only
    # literals that would break outright on Oracle (no now() function, no
    # bare `true` keyword pre-23c). Replaced with sa.func.now() / sa.true(),
    # which compile correctly per dialect. The open-ended-uniqueness index
    # is branched explicitly below for the same reason: autogenerate only
    # captured the Postgres form, since that's the only one that physically
    # existed in the database it reflected.
    op.create_table('identity_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entra_subject', sa.String(length=320), nullable=False),
    sa.Column('environment', sa.String(length=10), nullable=False),
    sa.Column('target_system', sa.String(length=10), nullable=False),
    sa.Column('mapped_role', sa.String(length=240), nullable=False),
    sa.Column('resolution_source', sa.String(length=24), server_default='resolved_from_source', nullable=False),
    sa.Column('effective_start_date', sa.DateTime(timezone=True).with_variant(oracle.TIMESTAMP(timezone=True), 'oracle'), nullable=False),
    sa.Column('effective_end_date', sa.DateTime(timezone=True).with_variant(oracle.TIMESTAMP(timezone=True), 'oracle'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True).with_variant(oracle.TIMESTAMP(timezone=True), 'oracle'), server_default=sa.func.now(), nullable=False),
    sa.Column('created_by', sa.String(length=320), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True).with_variant(oracle.TIMESTAMP(timezone=True), 'oracle'), nullable=True),
    sa.Column('updated_by', sa.String(length=320), nullable=True),
    sa.CheckConstraint("environment IN ('dev', 'test', 'uat', 'prod')", name='ck_identity_mappings_environment'),
    sa.CheckConstraint("resolution_source IN ('resolved_from_source', 'manually_overridden')", name='ck_identity_mappings_resolution_source'),
    sa.CheckConstraint("target_system IN ('ebs', 'fusion')", name='ck_identity_mappings_target_system'),
    sa.CheckConstraint('effective_end_date IS NULL OR effective_end_date > effective_start_date', name='ck_identity_mappings_date_order'),
    sa.PrimaryKeyConstraint('id')
    )

    bind = op.get_bind()
    if bind.dialect.name == "oracle":
        op.create_index(
            'ux_identity_mappings_open_ended', 'identity_mappings',
            [sa.text(
                "(CASE WHEN effective_end_date IS NULL THEN "
                "entra_subject || ':' || environment || ':' || target_system END)"
            )],
            unique=True,
        )
    else:
        op.create_index(
            'ux_identity_mappings_open_ended', 'identity_mappings',
            ['entra_subject', 'environment', 'target_system'],
            unique=True, postgresql_where=sa.text('effective_end_date IS NULL'),
        )

    op.create_table('identity_mapping_org_scope',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identity_mapping_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.Column('org_name', sa.String(length=240), nullable=True),
    sa.Column('resolved_from_source', sa.Boolean(), server_default=sa.true(), nullable=False),
    sa.ForeignKeyConstraint(['identity_mapping_id'], ['identity_mappings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identity_mapping_id', 'org_id', name='ux_mapping_org_scope_no_dupes')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('identity_mapping_org_scope')
    op.drop_index('ux_identity_mappings_open_ended', table_name='identity_mappings')
    op.drop_table('identity_mappings')
    # ### end Alembic commands ###
