"""add local admin accounts

Revision ID: e6d741f37460
Revises: 7b852db3e538
Create Date: 2026-08-31 23:58:56.377141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import oracle

# revision identifiers, used by Alembic.
revision: str = 'e6d741f37460'
down_revision: Union[str, Sequence[str], None] = '7b852db3e538'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default values hand-corrected after autogenerate: it reflects
    # now()/true as raw Postgres-only text() literals rather than the
    # portable func.now()/true() models.py actually declares — same fix
    # as every other migration in this project that touches a
    # created_at/is_active-shaped column (see e.g. 8e8baf37c76a). Left
    # as-is, this would emit `now()`/bare `true` verbatim against an
    # Oracle target, neither of which Oracle understands the same way.
    op.create_table('admin_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.true(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True).with_variant(oracle.TIMESTAMP(timezone=True), 'oracle'), server_default=sa.func.now(), nullable=False),
    sa.Column('created_by', sa.String(length=320), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True).with_variant(oracle.TIMESTAMP(timezone=True), 'oracle'), nullable=True),
    sa.Column('updated_by', sa.String(length=320), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username', name='ux_admin_accounts_username')
    )
    # ### end Alembic commands ###

    # management-api's runtime role only needs to read this table (to
    # check a login attempt) — never INSERT or UPDATE it, so a bug or an
    # injection in that process can't create or modify its own admin
    # accounts. Creating the first account is a separate, out-of-band
    # operation (management-api/scripts/create_admin.py), run with a
    # more privileged connection, not this one.
    #
    # Guarded by existence rather than assumed present: mgmt_identity_writer
    # itself isn't provisioned by any tracked migration (it predates this
    # one, created ad hoc against this project's dev database) — a fresh
    # environment that provisions roles some other way shouldn't have this
    # migration fail outright over it.
    bind = op.get_bind()
    if bind.dialect.name != "oracle":
        op.execute(
            """
            DO $$
            BEGIN
                IF EXISTS (SELECT FROM pg_roles WHERE rolname = 'mgmt_identity_writer') THEN
                    GRANT SELECT ON admin_accounts TO mgmt_identity_writer;
                END IF;
            END $$;
            """
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin_accounts')
    # ### end Alembic commands ###
