"""initial audit log schema

Revision ID: 5426635c30f6
Revises: 
Create Date: 2026-08-31 15:19:22.992222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import oracle

from db.types import PortableJSON
from db import provisioning

# revision identifiers, used by Alembic.
revision: str = '5426635c30f6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Hand-corrected after autogenerate, same reason as identity-service's
    # initial migration: sa.text('now()') was reflected from the live
    # Postgres default and is Postgres-only syntax (Oracle has no now()
    # function); sa.func.now() compiles correctly per dialect.
    #
    # The table intentionally has no primary key yet at this point — see
    # db/provisioning.py for why it's added afterward via op.execute()
    # rather than declared in create_table.
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('correlation_id', sa.String(length=36), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True).with_variant(oracle.TIMESTAMP(timezone=True), 'oracle'), server_default=sa.func.now(), nullable=False),
    sa.Column('tool_name', sa.String(length=120), nullable=False),
    sa.Column('subject', sa.String(length=320), nullable=False),
    sa.Column('environment', sa.String(length=10), nullable=False),
    sa.Column('target_system', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('effective_org_ids', PortableJSON(), nullable=True),
    sa.Column('params', PortableJSON(), nullable=True),
    sa.Column('error_message', sa.String(length=4000), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.CheckConstraint("status IN ('ok', 'denied', 'no_identity_mapping', 'error')", name='ck_audit_log_status'),
    postgresql_partition_by='RANGE (occurred_at)'
    )
    op.create_index('ix_audit_log_correlation_id', 'audit_log', ['correlation_id'], unique=False)
    op.create_index('ix_audit_log_subject_env', 'audit_log', ['subject', 'environment'], unique=False)

    bind = op.get_bind()
    if bind.dialect.name == "oracle":
        op.execute(provisioning.ADD_PRIMARY_KEY_ORACLE)
    else:
        op.execute(provisioning.ADD_PRIMARY_KEY_POSTGRESQL)
        op.execute(provisioning.CREATE_INITIAL_PARTITIONS)
        op.execute(provisioning.CREATE_APPEND_ONLY_ROLES_AND_GRANTS)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    if bind.dialect.name != "oracle":
        op.execute("DROP ROLE IF EXISTS ebsmcp_audit_writer")
        op.execute("DROP ROLE IF EXISTS ebsmcp_audit_reader")
    op.drop_index('ix_audit_log_subject_env', table_name='audit_log')
    op.drop_index('ix_audit_log_correlation_id', table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
